version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native protocol
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=admin           # Optional: Define if using a custom user
      - CLICKHOUSE_PASSWORD=supersecret # Optional: Define if using a custom password

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestion-api
    ports:
      - "8080:8080"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=supersecret
      - CLICKHOUSE_PORT=9000
    depends_on:
      - clickhouse

volumes:
  clickhouse-data:
